INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Anantapur', 'Anantapur', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chittoor', 'Chittoor', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Godavari', 'East Godavari', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Guntur', 'Guntur', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Krishna', 'Krishna', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kurnool', 'Kurnool', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Prakasam', 'Prakasam', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Srikakulam', 'Srikakulam', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sri Potti Sriramulu Nellore', 'Sri Potti Sriramulu Nellore', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Visakhapatnam', 'Visakhapatnam', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vizianagaram', 'Vizianagaram', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Godavari', 'West Godavari', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('YSR District, Kadapa (Cuddapah)', 'YSR District, Kadapa (Cuddapah)', 9, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Anjaw', 'Anjaw', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Changlang', 'Changlang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dibang Valley', 'Dibang Valley', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Kameng', 'East Kameng', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Siang', 'East Siang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kra Daadi', 'Kra Daadi', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kurung Kumey', 'Kurung Kumey', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lohit', 'Lohit', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Longding', 'Longding', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lower Dibang Valley', 'Lower Dibang Valley', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lower Siang', 'Lower Siang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lower Subansiri', 'Lower Subansiri', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Namsai', 'Namsai', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Papum Pare', 'Papum Pare', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Siang', 'Siang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tawang', 'Tawang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tirap', 'Tirap', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Upper Siang', 'Upper Siang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Upper Subansiri', 'Upper Subansiri', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Kameng', 'West Kameng', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Siang', 'West Siang', 10, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Baksa', 'Baksa', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Barpeta', 'Barpeta', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Biswanath', 'Biswanath', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bongaigaon', 'Bongaigaon', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Cachar', 'Cachar', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Charaideo', 'Charaideo', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chirang', 'Chirang', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Darrang', 'Darrang', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhemaji', 'Dhemaji', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhubri', 'Dhubri', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dibrugarh', 'Dibrugarh', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dima Hasao (North Cachar Hills)', 'Dima Hasao (North Cachar Hills)', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Goalpara', 'Goalpara', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Golaghat', 'Golaghat', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hailakandi', 'Hailakandi', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hojai', 'Hojai', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jorhat', 'Jorhat', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kamrup', 'Kamrup', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kamrup Metropolitan', 'Kamrup Metropolitan', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karbi Anglong', 'Karbi Anglong', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karimganj', 'Karimganj', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kokrajhar', 'Kokrajhar', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lakhimpur', 'Lakhimpur', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Majuli', 'Majuli', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Morigaon', 'Morigaon', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nagaon', 'Nagaon', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nalbari', 'Nalbari', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sivasagar', 'Sivasagar', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sonitpur', 'Sonitpur', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Salamara-Mankachar', 'South Salamara-Mankachar', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tinsukia', 'Tinsukia', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Udalguri', 'Udalguri', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Karbi Anglong', 'West Karbi Anglong', 11, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Araria', 'Araria', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Arwal', 'Arwal', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Aurangabad', 'Aurangabad', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Banka', 'Banka', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Begusarai', 'Begusarai', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhagalpur', 'Bhagalpur', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhojpur', 'Bhojpur', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Buxar', 'Buxar', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Darbhanga', 'Darbhanga', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Champaran (Motihari)', 'East Champaran (Motihari)', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gaya', 'Gaya', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gopalganj', 'Gopalganj', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jamui', 'Jamui', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jehanabad', 'Jehanabad', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kaimur (Bhabua)', 'Kaimur (Bhabua)', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Katihar', 'Katihar', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khagaria', 'Khagaria', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kishanganj', 'Kishanganj', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lakhisarai', 'Lakhisarai', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Madhepura', 'Madhepura', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Madhubani', 'Madhubani', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Munger (Monghyr)', 'Munger (Monghyr)', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Muzaffarpur', 'Muzaffarpur', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nalanda', 'Nalanda', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nawada', 'Nawada', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Patna', 'Patna', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Purnia (Purnea)', 'Purnia (Purnea)', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rohtas', 'Rohtas', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Saharsa', 'Saharsa', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Samastipur', 'Samastipur', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Saran', 'Saran', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sheikhpura', 'Sheikhpura', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sheohar', 'Sheohar', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sitamarhi', 'Sitamarhi', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Siwan', 'Siwan', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Supaul', 'Supaul', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vaishali', 'Vaishali', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Champaran', 'West Champaran', 12, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balod', 'Balod', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Baloda Bazar', 'Baloda Bazar', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balrampur', 'Balrampur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bastar', 'Bastar', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bemetara', 'Bemetara', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bijapur', 'Bijapur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bilaspur', 'Bilaspur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dantewada (South Bastar)', 'Dantewada (South Bastar)', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhamtari', 'Dhamtari', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Durg', 'Durg', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gariyaband', 'Gariyaband', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Janjgir-Champa', 'Janjgir-Champa', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jashpur', 'Jashpur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kabirdham (Kawardha)', 'Kabirdham (Kawardha)', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanker (North Bastar)', 'Kanker (North Bastar)', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kondagaon', 'Kondagaon', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Korba', 'Korba', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Korea (Koriya)', 'Korea (Koriya)', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahasamund', 'Mahasamund', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mungeli', 'Mungeli', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Narayanpur', 'Narayanpur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Raigarh', 'Raigarh', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Raipur', 'Raipur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajnandgaon', 'Rajnandgaon', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sukma', 'Sukma', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Surajpur', 'Surajpur', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Surguja', 'Surguja', 13, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North Goa', 'North Goa', 14, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Goa', 'South Goa', 14, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ahmedabad', 'Ahmedabad', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Amreli', 'Amreli', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Anand', 'Anand', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Aravalli', 'Aravalli', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Banaskantha (Palanpur)', 'Banaskantha (Palanpur)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bharuch', 'Bharuch', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhavnagar', 'Bhavnagar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Botad', 'Botad', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chhota Udepur', 'Chhota Udepur', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dahod', 'Dahod', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dangs (Ahwa)', 'Dangs (Ahwa)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Devbhoomi Dwarka', 'Devbhoomi Dwarka', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gandhinagar', 'Gandhinagar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gir Somnath', 'Gir Somnath', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jamnagar', 'Jamnagar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Junagadh', 'Junagadh', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kachchh', 'Kachchh', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kheda (Nadiad)', 'Kheda (Nadiad)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahisagar', 'Mahisagar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mehsana', 'Mehsana', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Morbi', 'Morbi', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Narmada (Rajpipla)', 'Narmada (Rajpipla)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Navsari', 'Navsari', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Panchmahal (Godhra)', 'Panchmahal (Godhra)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Patan', 'Patan', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Porbandar', 'Porbandar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajkot', 'Rajkot', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sabarkantha (Himmatnagar)', 'Sabarkantha (Himmatnagar)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Surat', 'Surat', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Surendranagar', 'Surendranagar', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tapi (Vyara)', 'Tapi (Vyara)', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vadodara', 'Vadodara', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Valsad', 'Valsad', 15, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ambala', 'Ambala', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhiwani', 'Bhiwani', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Charkhi Dadri', 'Charkhi Dadri', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Faridabad', 'Faridabad', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Fatehabad', 'Fatehabad', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gurgaon', 'Gurgaon', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hisar', 'Hisar', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jhajjar', 'Jhajjar', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jind', 'Jind', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kaithal', 'Kaithal', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karnal', 'Karnal', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kurukshetra', 'Kurukshetra', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahendragarh', 'Mahendragarh', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mewat', 'Mewat', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Palwal', 'Palwal', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Panchkula', 'Panchkula', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Panipat', 'Panipat', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rewari', 'Rewari', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rohtak', 'Rohtak', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sirsa', 'Sirsa', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sonipat', 'Sonipat', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Yamunanagar', 'Yamunanagar', 16, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bilaspur', 'Bilaspur', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chamba', 'Chamba', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hamirpur', 'Hamirpur', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kangra', 'Kangra', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kinnaur', 'Kinnaur', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kullu', 'Kullu', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lahaul & Spiti', 'Lahaul & Spiti', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mandi', 'Mandi', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shimla', 'Shimla', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sirmaur (Sirmour)', 'Sirmaur (Sirmour)', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Solan', 'Solan', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Una', 'Una', 17, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Anantnag', 'Anantnag', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bandipore', 'Bandipore', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Baramulla', 'Baramulla', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Budgam', 'Budgam', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Doda', 'Doda', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ganderbal', 'Ganderbal', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jammu', 'Jammu', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kargil', 'Kargil', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kathua', 'Kathua', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kishtwar', 'Kishtwar', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kulgam', 'Kulgam', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kupwara', 'Kupwara', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Leh', 'Leh', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Poonch', 'Poonch', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pulwama', 'Pulwama', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajouri', 'Rajouri', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ramban', 'Ramban', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Reasi', 'Reasi', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Samba', 'Samba', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shopian', 'Shopian', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Srinagar', 'Srinagar', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Udhampur', 'Udhampur', 18, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bokaro', 'Bokaro', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chatra', 'Chatra', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Deoghar', 'Deoghar', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhanbad', 'Dhanbad', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dumka', 'Dumka', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Singhbhum', 'East Singhbhum', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Garhwa', 'Garhwa', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Giridih', 'Giridih', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Godda', 'Godda', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gumla', 'Gumla', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hazaribag', 'Hazaribag', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jamtara', 'Jamtara', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khunti', 'Khunti', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Koderma', 'Koderma', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Latehar', 'Latehar', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lohardaga', 'Lohardaga', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pakur', 'Pakur', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Palamu', 'Palamu', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ramgarh', 'Ramgarh', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ranchi', 'Ranchi', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sahibganj', 'Sahibganj', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Seraikela-Kharsawan', 'Seraikela-Kharsawan', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Simdega', 'Simdega', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Singhbhum', 'West Singhbhum', 19, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bagalkot', 'Bagalkot', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ballari (Bellary)', 'Ballari (Bellary)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Belagavi (Belgaum)', 'Belagavi (Belgaum)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bengaluru (Bangalore) Rural', 'Bengaluru (Bangalore) Rural', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bengaluru (Bangalore) Urban', 'Bengaluru (Bangalore) Urban', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bidar', 'Bidar', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chamarajanagar', 'Chamarajanagar', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chikballapur', 'Chikballapur', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chikkamagaluru (Chikmagalur)', 'Chikkamagaluru (Chikmagalur)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chitradurga', 'Chitradurga', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dakshina Kannada', 'Dakshina Kannada', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Davangere', 'Davangere', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dharwad', 'Dharwad', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gadag', 'Gadag', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hassan', 'Hassan', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Haveri', 'Haveri', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kalaburagi (Gulbarga)', 'Kalaburagi (Gulbarga)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kodagu', 'Kodagu', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kolar', 'Kolar', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Koppal', 'Koppal', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mandya', 'Mandya', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mysuru (Mysore)', 'Mysuru (Mysore)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Raichur', 'Raichur', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ramanagara', 'Ramanagara', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shivamogga (Shimoga)', 'Shivamogga (Shimoga)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tumakuru (Tumkur)', 'Tumakuru (Tumkur)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Udupi', 'Udupi', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Uttara Kannada (Karwar)', 'Uttara Kannada (Karwar)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vijayapura (Bijapur)', 'Vijayapura (Bijapur)', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Yadgir', 'Yadgir', 20, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Alappuzha', 'Alappuzha', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ernakulam', 'Ernakulam', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Idukki', 'Idukki', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kannur', 'Kannur', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kasaragod', 'Kasaragod', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kollam', 'Kollam', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kottayam', 'Kottayam', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kozhikode', 'Kozhikode', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Malappuram', 'Malappuram', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Palakkad', 'Palakkad', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pathanamthitta', 'Pathanamthitta', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thiruvananthapuram', 'Thiruvananthapuram', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thrissur', 'Thrissur', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Wayanad', 'Wayanad', 21, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Agar Malwa', 'Agar Malwa', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Alirajpur', 'Alirajpur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Anuppur', 'Anuppur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ashoknagar', 'Ashoknagar', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balaghat', 'Balaghat', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Barwani', 'Barwani', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Betul', 'Betul', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhind', 'Bhind', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhopal', 'Bhopal', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Burhanpur', 'Burhanpur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chhatarpur', 'Chhatarpur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chhindwara', 'Chhindwara', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Damoh', 'Damoh', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Datia', 'Datia', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dewas', 'Dewas', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhar', 'Dhar', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dindori', 'Dindori', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Guna', 'Guna', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gwalior', 'Gwalior', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Harda', 'Harda', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hoshangabad', 'Hoshangabad', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Indore', 'Indore', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jabalpur', 'Jabalpur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jhabua', 'Jhabua', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Katni', 'Katni', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khandwa', 'Khandwa', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khargone', 'Khargone', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mandla', 'Mandla', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mandsaur', 'Mandsaur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Morena', 'Morena', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Narsinghpur', 'Narsinghpur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Neemuch', 'Neemuch', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Panna', 'Panna', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Raisen', 'Raisen', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajgarh', 'Rajgarh', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ratlam', 'Ratlam', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rewa', 'Rewa', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sagar', 'Sagar', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Satna', 'Satna', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sehore', 'Sehore', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Seoni', 'Seoni', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shahdol', 'Shahdol', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shajapur', 'Shajapur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sheopur', 'Sheopur', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shivpuri', 'Shivpuri', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sidhi', 'Sidhi', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Singrauli', 'Singrauli', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tikamgarh', 'Tikamgarh', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ujjain', 'Ujjain', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Umaria', 'Umaria', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vidisha', 'Vidisha', 22, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ahmednagar', 'Ahmednagar', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Akola', 'Akola', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Amravati', 'Amravati', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Aurangabad', 'Aurangabad', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Beed', 'Beed', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhandara', 'Bhandara', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Buldhana', 'Buldhana', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chandrapur', 'Chandrapur', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhule', 'Dhule', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gadchiroli', 'Gadchiroli', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gondia', 'Gondia', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hingoli', 'Hingoli', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalgaon', 'Jalgaon', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalna', 'Jalna', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kolhapur', 'Kolhapur', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Latur', 'Latur', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mumbai City', 'Mumbai City', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mumbai Suburban', 'Mumbai Suburban', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nagpur', 'Nagpur', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nanded', 'Nanded', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nandurbar', 'Nandurbar', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nashik', 'Nashik', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Osmanabad', 'Osmanabad', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Palghar', 'Palghar', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Parbhani', 'Parbhani', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pune', 'Pune', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Raigad', 'Raigad', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ratnagiri', 'Ratnagiri', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sangli', 'Sangli', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Satara', 'Satara', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sindhudurg', 'Sindhudurg', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Solapur', 'Solapur', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thane', 'Thane', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Wardha', 'Wardha', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Washim', 'Washim', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Yavatmal', 'Yavatmal', 23, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bishnupur', 'Bishnupur', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chandel', 'Chandel', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Churachandpur', 'Churachandpur', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Imphal East', 'Imphal East', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Imphal West', 'Imphal West', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jiribam', 'Jiribam', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kakching', 'Kakching', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kamjong', 'Kamjong', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kangpokpi', 'Kangpokpi', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Noney', 'Noney', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pherzawl', 'Pherzawl', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Senapati', 'Senapati', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tamenglong', 'Tamenglong', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tengnoupal', 'Tengnoupal', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thoubal', 'Thoubal', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ukhrul', 'Ukhrul', 24, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Garo Hills', 'East Garo Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Jaintia Hills', 'East Jaintia Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Khasi Hills', 'East Khasi Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North Garo Hills', 'North Garo Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ri Bhoi', 'Ri Bhoi', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Garo Hills', 'South Garo Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South West Garo Hills', 'South West Garo Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South West Khasi Hills', 'South West Khasi Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Garo Hills', 'West Garo Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Jaintia Hills', 'West Jaintia Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Khasi Hills', 'West Khasi Hills', 25, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Aizawl', 'Aizawl', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Champhai', 'Champhai', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kolasib', 'Kolasib', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lawngtlai', 'Lawngtlai', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lunglei', 'Lunglei', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mamit', 'Mamit', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Saiha', 'Saiha', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Serchhip', 'Serchhip', 26, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dimapur', 'Dimapur', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kiphire', 'Kiphire', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kohima', 'Kohima', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Longleng', 'Longleng', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mokokchung', 'Mokokchung', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mon', 'Mon', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Peren', 'Peren', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Phek', 'Phek', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tuensang', 'Tuensang', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Wokha', 'Wokha', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Zunheboto', 'Zunheboto', 27, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Angul', 'Angul', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balangir', 'Balangir', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balasore', 'Balasore', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bargarh', 'Bargarh', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhadrak', 'Bhadrak', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Boudh', 'Boudh', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Cuttack', 'Cuttack', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Deogarh', 'Deogarh', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhenkanal', 'Dhenkanal', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gajapati', 'Gajapati', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ganjam', 'Ganjam', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jagatsinghapur', 'Jagatsinghapur', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jajpur', 'Jajpur', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jharsuguda', 'Jharsuguda', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kalahandi', 'Kalahandi', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kandhamal', 'Kandhamal', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kendrapara', 'Kendrapara', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kendujhar (Keonjhar)', 'Kendujhar (Keonjhar)', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khordha', 'Khordha', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Koraput', 'Koraput', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Malkangiri', 'Malkangiri', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mayurbhanj', 'Mayurbhanj', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nabarangpur', 'Nabarangpur', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nayagarh', 'Nayagarh', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nuapada', 'Nuapada', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Puri', 'Puri', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rayagada', 'Rayagada', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sambalpur', 'Sambalpur', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sonepur', 'Sonepur', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sundargarh', 'Sundargarh', 28, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Amritsar', 'Amritsar', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Barnala', 'Barnala', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bathinda', 'Bathinda', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Faridkot', 'Faridkot', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Fatehgarh Sahib', 'Fatehgarh Sahib', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Fazilka', 'Fazilka', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ferozepur', 'Ferozepur', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gurdaspur', 'Gurdaspur', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hoshiarpur', 'Hoshiarpur', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalandhar', 'Jalandhar', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kapurthala', 'Kapurthala', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ludhiana', 'Ludhiana', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mansa', 'Mansa', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Moga', 'Moga', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Muktsar', 'Muktsar', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nawanshahr (Shahid Bhagat Singh Nagar)', 'Nawanshahr (Shahid Bhagat Singh Nagar)', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pathankot', 'Pathankot', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Patiala', 'Patiala', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rupnagar', 'Rupnagar', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sahibzada Ajit Singh Nagar (Mohali)', 'Sahibzada Ajit Singh Nagar (Mohali)', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sangrur', 'Sangrur', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tarn Taran', 'Tarn Taran', 29, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ajmer', 'Ajmer', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Alwar', 'Alwar', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Banswara', 'Banswara', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Baran', 'Baran', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Barmer', 'Barmer', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bharatpur', 'Bharatpur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhilwara', 'Bhilwara', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bikaner', 'Bikaner', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bundi', 'Bundi', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chittorgarh', 'Chittorgarh', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Churu', 'Churu', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dausa', 'Dausa', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dholpur', 'Dholpur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dungarpur', 'Dungarpur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hanumangarh', 'Hanumangarh', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jaipur', 'Jaipur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jaisalmer', 'Jaisalmer', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalore', 'Jalore', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jhalawar', 'Jhalawar', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jhunjhunu', 'Jhunjhunu', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jodhpur', 'Jodhpur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karauli', 'Karauli', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kota', 'Kota', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nagaur', 'Nagaur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pali', 'Pali', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pratapgarh', 'Pratapgarh', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajsamand', 'Rajsamand', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sawai Madhopur', 'Sawai Madhopur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sikar', 'Sikar', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sirohi', 'Sirohi', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sri Ganganagar', 'Sri Ganganagar', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tonk', 'Tonk', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Udaipur', 'Udaipur', 30, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Sikkim', 'East Sikkim', 31, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North Sikkim', 'North Sikkim', 31, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Sikkim', 'South Sikkim', 31, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Sikkim', 'West Sikkim', 31, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ariyalur', 'Ariyalur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chennai', 'Chennai', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Coimbatore', 'Coimbatore', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Cuddalore', 'Cuddalore', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dharmapuri', 'Dharmapuri', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dindigul', 'Dindigul', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Erode', 'Erode', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanchipuram', 'Kanchipuram', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanyakumari', 'Kanyakumari', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karur', 'Karur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Krishnagiri', 'Krishnagiri', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Madurai', 'Madurai', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nagapattinam', 'Nagapattinam', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Namakkal', 'Namakkal', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nilgiris', 'Nilgiris', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Perambalur', 'Perambalur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pudukkottai', 'Pudukkottai', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ramanathapuram', 'Ramanathapuram', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Salem', 'Salem', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sivaganga', 'Sivaganga', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thanjavur', 'Thanjavur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Theni', 'Theni', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Thoothukudi (Tuticorin)', 'Thoothukudi (Tuticorin)', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tiruchirappalli', 'Tiruchirappalli', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tirunelveli', 'Tirunelveli', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tiruppur', 'Tiruppur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tiruvallur', 'Tiruvallur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tiruvannamalai', 'Tiruvannamalai', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tiruvarur', 'Tiruvarur', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vellore', 'Vellore', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Viluppuram', 'Viluppuram', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Virudhunagar', 'Virudhunagar', 32, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dhalai', 'Dhalai', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gomati', 'Gomati', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khowai', 'Khowai', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North Tripura', 'North Tripura', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sepahijala', 'Sepahijala', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Tripura', 'South Tripura', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Unakoti', 'Unakoti', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Tripura', 'West Tripura', 33, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Almora', 'Almora', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bageshwar', 'Bageshwar', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chamoli', 'Chamoli', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Champawat', 'Champawat', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dehradun', 'Dehradun', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Haridwar', 'Haridwar', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nainital', 'Nainital', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pauri Garhwal', 'Pauri Garhwal', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pithoragarh', 'Pithoragarh', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rudraprayag', 'Rudraprayag', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Tehri Garhwal', 'Tehri Garhwal', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Udham Singh Nagar', 'Udham Singh Nagar', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Uttarkashi', 'Uttarkashi', 34, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Agra', 'Agra', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Aligarh', 'Aligarh', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Allahabad', 'Allahabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ambedkar Nagar', 'Ambedkar Nagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Amethi (Chatrapati Sahuji Mahraj Nagar)', 'Amethi (Chatrapati Sahuji Mahraj Nagar)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Amroha (J.P. Nagar)', 'Amroha (J.P. Nagar)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Auraiya', 'Auraiya', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Azamgarh', 'Azamgarh', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Baghpat', 'Baghpat', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bahraich', 'Bahraich', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ballia', 'Ballia', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Balrampur', 'Balrampur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Banda', 'Banda', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Barabanki', 'Barabanki', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bareilly', 'Bareilly', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Basti', 'Basti', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhadohi', 'Bhadohi', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bijnor', 'Bijnor', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Budaun', 'Budaun', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bulandshahr', 'Bulandshahr', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chandauli', 'Chandauli', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chitrakoot', 'Chitrakoot', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Deoria', 'Deoria', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Etah', 'Etah', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Etawah', 'Etawah', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Faizabad', 'Faizabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Farrukhabad', 'Farrukhabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Fatehpur', 'Fatehpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Firozabad', 'Firozabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gautam Buddha Nagar', 'Gautam Buddha Nagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ghaziabad', 'Ghaziabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Ghazipur', 'Ghazipur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gonda', 'Gonda', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Gorakhpur', 'Gorakhpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hamirpur', 'Hamirpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hapur (Panchsheel Nagar)', 'Hapur (Panchsheel Nagar)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hardoi', 'Hardoi', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hathras', 'Hathras', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalaun', 'Jalaun', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jaunpur', 'Jaunpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jhansi', 'Jhansi', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kannauj', 'Kannauj', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanpur Dehat', 'Kanpur Dehat', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanpur Nagar', 'Kanpur Nagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kanshiram Nagar (Kasganj)', 'Kanshiram Nagar (Kasganj)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kaushambi', 'Kaushambi', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kushinagar (Padrauna)', 'Kushinagar (Padrauna)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lakhimpur - Kheri', 'Lakhimpur - Kheri', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lalitpur', 'Lalitpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lucknow', 'Lucknow', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Maharajganj', 'Maharajganj', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahoba', 'Mahoba', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mainpuri', 'Mainpuri', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mathura', 'Mathura', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mau', 'Mau', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Meerut', 'Meerut', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mirzapur', 'Mirzapur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Moradabad', 'Moradabad', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Muzaffarnagar', 'Muzaffarnagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pilibhit', 'Pilibhit', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pratapgarh', 'Pratapgarh', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('RaeBareli', 'RaeBareli', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rampur', 'Rampur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Saharanpur', 'Saharanpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sambhal (Bhim Nagar)', 'Sambhal (Bhim Nagar)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sant Kabir Nagar', 'Sant Kabir Nagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shahjahanpur', 'Shahjahanpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shamali (Prabuddh Nagar)', 'Shamali (Prabuddh Nagar)', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shravasti', 'Shravasti', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Siddharth Nagar', 'Siddharth Nagar', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sitapur', 'Sitapur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sonbhadra', 'Sonbhadra', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sultanpur', 'Sultanpur', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Unnao', 'Unnao', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Varanasi', 'Varanasi', 35, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Alipurduar', 'Alipurduar', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bankura', 'Bankura', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Birbhum', 'Birbhum', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Burdwan (Bardhaman)', 'Burdwan (Bardhaman)', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Cooch Behar', 'Cooch Behar', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dakshin Dinajpur (South Dinajpur)', 'Dakshin Dinajpur (South Dinajpur)', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Darjeeling', 'Darjeeling', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hooghly', 'Hooghly', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Howrah', 'Howrah', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jalpaiguri', 'Jalpaiguri', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kalimpong', 'Kalimpong', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kolkata', 'Kolkata', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Malda', 'Malda', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Murshidabad', 'Murshidabad', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nadia', 'Nadia', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North 24 Parganas', 'North 24 Parganas', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Paschim Medinipur (West Medinipur)', 'Paschim Medinipur (West Medinipur)', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Purba Medinipur (East Medinipur)', 'Purba Medinipur (East Medinipur)', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Purulia', 'Purulia', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South 24 Parganas', 'South 24 Parganas', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Uttar Dinajpur (North Dinajpur)', 'Uttar Dinajpur (North Dinajpur)', 36, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nicobar', 'Nicobar', 37, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North and Middle Andaman', 'North and Middle Andaman', 37, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Andaman', 'South Andaman', 37, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Chandigarh', 'Chandigarh', 38, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli', 39, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Daman', 'Daman', 40, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Diu', 'Diu', 40, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Central Delhi', 'Central Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('East Delhi', 'East Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('New Delhi', 'New Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North Delhi', 'North Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North East Delhi', 'North East Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('North West Delhi', 'North West Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Shahdara', 'Shahdara', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South Delhi', 'South Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South East Delhi', 'South East Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('South West Delhi', 'South West Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('West Delhi', 'West Delhi', 41, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Lakshadweep', 'Lakshadweep', 42, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karaikal', 'Karaikal', 43, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahe', 'Mahe', 43, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Pondicherry', 'Pondicherry', 43, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Yanam', 'Yanam', 43, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Adilabad', 'Adilabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Bhadradri Kothagudem', 'Bhadradri Kothagudem', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Hyderabad', 'Hyderabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jagtial', 'Jagtial', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jangaon', 'Jangaon', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jayashankar Bhoopalpally', 'Jayashankar Bhoopalpally', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Jogulamba Gadwal', 'Jogulamba Gadwal', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Kamareddy', 'Kamareddy', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Karimnagar', 'Karimnagar', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Khammam', 'Khammam', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Komaram Bheem Asifabad', 'Komaram Bheem Asifabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahabubabad', 'Mahabubabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mahabubnagar', 'Mahabubnagar', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Mancherial', 'Mancherial', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Medak', 'Medak', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Medchal', 'Medchal', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nagarkurnool', 'Nagarkurnool', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nalgonda', 'Nalgonda', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nirmal', 'Nirmal', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Nizamabad', 'Nizamabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Peddapalli', 'Peddapalli', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rajanna Sircilla', 'Rajanna Sircilla', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Rangareddy', 'Rangareddy', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Sangareddy', 'Sangareddy', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Siddipet', 'Siddipet', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Suryapet', 'Suryapet', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Vikarabad', 'Vikarabad', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Wanaparthy', 'Wanaparthy', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Warangal (Rural)', 'Warangal (Rural)', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Warangal (Urban)', 'Warangal (Urban)', 44, 3, 1);
INSERT INTO district (`code`, `description`, `stateID`, `status`, `createdBy`) VALUES ('Yadadri Bhuvanagiri', 'Yadadri Bhuvanagiri', 44, 3, 1);

