INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Accountancy', 'Accountancy', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Arthashastra', 'Arthashastra', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Bhautik Vigyan', 'Bhautik Vigyan', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Bhautiki,Rasayan,Ganit', 'Bhautiki,Rasayan,Ganit', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Bhautiki,Rasayan,Jeev Vigyan', 'Bhautiki,Rasayan,Jeev Vigyan', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Bhugol', 'Bhugol', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Biology', 'Biology', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Business Studies', 'Business Studies', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Chemistry', 'Chemistry', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Computer Science', 'Computer Science', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Economics', 'Economics', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('English', 'English', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Environmental Studies', 'Environmental Studies', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Ganit', 'Ganit', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Geography', 'Geography', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Hindi', 'Hindi', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('History', 'History', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Itihas', 'Itihas', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Jeev Vigyan', 'Jeev Vigyan', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Mathematics', 'Mathematics', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Physics', 'Physics', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Physics,Chemistry,Biology', 'Physics,Chemistry,Biology', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Physics,Chemistry,Mathematics', 'Physics,Chemistry,Mathematics', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Political Science', 'Political Science', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Psychology', 'Psychology', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Rajneeti Vigyan', 'Rajneeti Vigyan', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Rasayan Vigyan', 'Rasayan Vigyan', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Sanskrit', 'Sanskrit', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Science', 'Science', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Social Science', 'Social Science', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Social Studies', 'Social Studies', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Sociology', 'Sociology', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Statistics', 'Statistics', 3, 1);
INSERT INTO itemtype (`code`, `description`, `status`, `createdBy`) VALUES ('Vigyan', 'Vigyan', 3, 1);